#!/bin/bash

# Setup
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | \
  sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update

sudo apt-get -y install mesos
sudo apt-get update && \
    apt-get install -y python libnss3 openjdk-7-jre-headless curl

sudo mkdir /opt/spark && \
    curl http://www.us.apache.org/dist/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.4.tgz \
    | tar -xzC /opt

